---
- name: Install prometheus node_exporter
  ansible.builtin.include_tasks: install.yaml
  tags:
    - prometheus
    - node_exporter

- name: UFW | open access to node_exporter
  ansible.builtin.include_tasks: ufw.yaml
  when: enable_ufw | bool
  tags:
    - prometheus
    - node_exporter
    - ufw
...
